# Generated by Django 5.0 on 2023-12-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailFiltering', '0002_checkmailtaskthreaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmailtaskthreaded',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailFiltering.serveur'),
        ),
    ]
